#!/usr/bin/env bash
# vim: set ft=ruby:

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby

class Niche
  def main(keyword)
    @reviews = $stdin.readlines.map(&:chomp).map{ |file| Review.from_file(File.readlines(file)) }
    @search = Search.new(keyword, @reviews)
    puts @search.to_s
  end
end

class Search
  attr_reader :keyword, :results

  def initialize(keyword, reviews)
    @keyword = keyword
    @results = reviews.map{ |review| review.search(keyword) }
  end

  def to_s
    @results.each(&:to_s)
  end
end

class Review
  def self.from_file(text)
    school, *reviews = *text.map(&:chomp)
    Review.new(school, reviews)
  end

  attr_reader :school, :reviews

  def initialize(school, reviews)
    @school = school
    @reviews = reviews
  end

  def search(keyword)
    Review.new(@school, @reviews.find_all{ |review| review.include?(keyword) })
  end

  def to_s()
    "#{@school}: #{@reviews.count} reviews"
  end
end

if $0 == __FILE__
  begin
    Niche.new.main(ARGV.first || "")
  rescue Interrupt
    exit(1)
  end
end
