#!/usr/bin/env bash
# vim: set ft=ruby:

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby

class Niche
  def main(keyword)
    @reviews = $stdin.readlines.map{ |file| Review.new(File.readlines(file.chomp)) }
    @search = Search.new(keyword, @reviews)
    puts @search.results
  end
end

class Search
  attr_reader :keyword, :results

  def initialize(keyword, reviews)
    @keyword = keyword
    @results = reviews.find_all{ |review| review.scan(keyword) }
  end
end

class Review
  attr_reader :school, :reviews

  def initialize(text)
    @school, *@reviews = *text.map(&:chomp)
  end

  def scan(keyword)
    @reviews.map{ |review| review.scan(keyword) }.flatten.count
  end

  def to_s()
    "#{@school}: #{@reviews.count} reviews"
  end
end

if $0 == __FILE__
  begin
    Niche.new.main(ARGV.first || "")
  rescue Interrupt
    exit(1)
  end
end
