#!/usr/bin/env bash
# vim: set ft=ruby:

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby

class Niche
  def main(keyword)
    @profiles = $stdin.readlines.map{ |file| Profile.from_file(File.readlines(file.chomp)) }
    @search = Search.new(keyword, @profiles)
    puts(@search.print())
  end
end

class Profile
  def self.from_file(lines)
    school, *reviews = *lines.map(&:chomp)
    Profile.new(school, reviews)
  end

  attr_reader :school, :reviews

  def initialize(school, reviews)
    @school = school
    @reviews = reviews
  end

  def search(keyword)
    results = @reviews.find_all{ |review| review.include?(keyword) }
    Profile.new(@school, results)
  end

  def to_s()
    "#{@school}: #{@reviews.count} reviews"
  end
end

class Search
  attr_reader :keyword, :results

  def initialize(keyword, profiles)
    @keyword = keyword
    @results = profiles.map{ |profile| profile.search(keyword) }.find_all{ |profile| profile.reviews.count != 0 }
  end

  def print()
    @results.sort_by{ |result| [-result.reviews.count, result.school] }.each(&:to_s)
  end

  def to_s()
    @results.each(&:to_s)
  end
end

if $0 == __FILE__
  begin
    Niche.new.main(*ARGV)
  rescue Interrupt
    exit(1)
  end
end
